# Makefile to build class 'helloworld' for Pure Data.
# Needs Makefile.pdlibbuilder as helper makefile for platform-dependent build
# settings and rules.

CXX = clang++

LLVM_COMPONENTS = support core irreader mcjit linker native

# library name
lib.name = jit_expr
common.sources = src/llvmcodegen/codegen.cc

#convert -I to -isystem so we don't get so many warnings.
llvmcflags = `llvm-config-5.0 --cxxflags | ruby -pe 'sub /-I/, "-isystem"'`
cflags = --std=c++11 ${llvmcflags} -isystem/usr/local/include/ -Isrc/ -Isrc/parse/ -Ibuild/src/parse/ -fexceptions -g

ldflags = `llvm-config-5.0 --ldflags` `llvm-config-5.0 --libs ${LLVM_COMPONENTS}` 
ldlibs += build/src/parse/libparse.a

# input source file (class name == source file basename)
class.sources = src/jit_expr.cpp

# all extra files to be included in binary distribution of the library
datafiles = README.md

# include Makefile.pdlibbuilder from submodule directory 'pd-lib-builder'
PDLIBBUILDER_DIR=pd-lib-builder/
include $(PDLIBBUILDER_DIR)/Makefile.pdlibbuilder
